#lang racket/base

(require libghostty
         rackunit)

(define (call-with-terminal procedure #:continuation-max-bytes [limit 0])
  (define terminal (make-terminal 40 4 #:continuation-max-bytes limit))
  (dynamic-wind void (lambda () (procedure terminal)) (lambda () (terminal-close! terminal))))

(define (ghostty-error-result procedure)
  (with-handlers ([exn:fail:ghostty? exn:fail:ghostty-result])
    (procedure)
    'no-error))

(define (capture-raised procedure)
  (with-handlers ([(lambda (_value) #t) values])
    (procedure)
    'returned))

(test-case "continuation policy defaults, constructor, runtime, and size_t boundaries"
  (call-with-terminal (lambda (terminal)
                        (check-equal? (terminal-continuation-max-bytes terminal) 0)
                        (check-true (terminal-vt-ground? terminal))
                        (check-equal? (ghostty-error-result (lambda ()
                                                              (terminal-continuation-bytes terminal)))
                                      'invalid-value)))
  (call-with-terminal #:continuation-max-bytes 17
                      (lambda (terminal)
                        (check-equal? (terminal-continuation-max-bytes terminal) 17)
                        (terminal-set-continuation-max-bytes! terminal 18446744073709551615)
                        (check-equal? (terminal-continuation-max-bytes terminal) 18446744073709551615)
                        (terminal-set-continuation-max-bytes! terminal 0)
                        (check-equal? (terminal-continuation-max-bytes terminal) 0)))
  (for ([invalid (in-list (list -1 1/2 18446744073709551616))])
    (check-exn exn:fail:contract? (lambda () (make-terminal 10 2 #:continuation-max-bytes invalid))))
  (call-with-terminal (lambda (terminal)
                        (for ([invalid (in-list (list -1 1/2 18446744073709551616))])
                          (check-exn exn:fail:contract?
                                     (lambda ()
                                       (terminal-set-continuation-max-bytes! terminal invalid)))))))

(test-case "ground, CSI, UTF-8, immutable copying, and copied lifetime"
  (define terminal (make-terminal 40 4 #:continuation-max-bytes 32))
  (define csi-copy #f)
  (define utf8-copy #f)
  (dynamic-wind void
                (lambda ()
                  (define empty (terminal-continuation-bytes terminal))
                  (check-equal? empty #"")
                  (check-true (immutable? empty))
                  (terminal-write! terminal #"plain\33[31")
                  (set! csi-copy (terminal-continuation-bytes terminal))
                  (check-equal? csi-copy #"\33[31")
                  (check-true (immutable? csi-copy))
                  (check-equal? (terminal-continuation-bytes terminal) csi-copy)
                  (terminal-write! terminal #"m")
                  (check-true (terminal-vt-ground? terminal))
                  (terminal-write! terminal (bytes #xf0 #x9f))
                  (set! utf8-copy (terminal-continuation-bytes terminal))
                  (check-equal? utf8-copy (bytes #xf0 #x9f))
                  (check-true (immutable? utf8-copy))
                  (terminal-write! terminal (bytes #x98 #x84))
                  (check-equal? (terminal-continuation-bytes terminal) #"")
                  (terminal-set-continuation-max-bytes! terminal 0))
                (lambda ()
                  (terminal-close! terminal)
                  (terminal-close! terminal)))
  (check-equal? csi-copy #"\33[31")
  (check-equal? utf8-copy (bytes #xf0 #x9f)))

(test-case "exact caps, overflow, lowering, raising, and repair rules"
  (call-with-terminal
   #:continuation-max-bytes 5
   (lambda (terminal)
     (terminal-write! terminal #"\33[123")
     (check-equal? (terminal-continuation-bytes terminal) #"\33[123")
     (terminal-write! terminal #"4")
     (check-equal? (ghostty-error-result (lambda () (terminal-continuation-bytes terminal)))
                   'invalid-value)
     (terminal-set-continuation-max-bytes! terminal 8)
     (check-equal? (ghostty-error-result (lambda () (terminal-continuation-bytes terminal)))
                   'invalid-value)
     (terminal-write! terminal #"\33[")
     (check-equal? (terminal-continuation-bytes terminal) #"\33[")
     (terminal-set-continuation-max-bytes! terminal 1)
     (check-equal? (ghostty-error-result (lambda () (terminal-continuation-bytes terminal)))
                   'invalid-value)
     (terminal-set-continuation-max-bytes! terminal 8)
     (check-equal? (ghostty-error-result (lambda () (terminal-continuation-bytes terminal)))
                   'invalid-value)
     (terminal-write! terminal #"m")
     (check-true (terminal-vt-ground? terminal))
     (check-equal? (terminal-continuation-bytes terminal) #"")))
  (call-with-terminal
   (lambda (terminal)
     (terminal-write! terminal #"\33[")
     (terminal-set-continuation-max-bytes! terminal 8)
     (check-equal? (ghostty-error-result (lambda () (terminal-continuation-bytes terminal)))
                   'invalid-value)
     (terminal-write! terminal #"\33[")
     (check-equal? (terminal-continuation-bytes terminal) #"\33[")
     (terminal-set-continuation-max-bytes! terminal 0)
     (terminal-set-continuation-max-bytes! terminal 8)
     (check-equal? (ghostty-error-result (lambda () (terminal-continuation-bytes terminal)))
                   'invalid-value)
     (terminal-write! terminal #"m")
     (check-equal? (terminal-continuation-bytes terminal) #""))))

(test-case "continuation replay is equivalent and suppresses committed effects"
  (define source (make-terminal 20 2 #:continuation-max-bytes 32))
  (define replay (make-terminal 20 2 #:continuation-max-bytes 32))
  (define source-bells 0)
  (define replay-bells 0)
  (dynamic-wind
   void
   (lambda ()
     (terminal-set-bell-handler! source (lambda () (set! source-bells (add1 source-bells))))
     (terminal-set-bell-handler! replay (lambda () (set! replay-bells (add1 replay-bells))))
     (terminal-write! source #"\a\33[31")
     (define continuation (terminal-continuation-bytes source))
     (check-equal? continuation #"\33[31")
     (check-equal? source-bells 1)
     (terminal-write! replay continuation)
     (check-equal? replay-bells 0)
     (terminal-write! source #"mX")
     (terminal-write! replay #"mX")
     (check-equal? (terminal->plain-text source) (terminal->plain-text replay))
     (check-equal? (terminal->plain-text replay) "X")
     (check-equal? (list source-bells replay-bells) '(1 0)))
   (lambda ()
     (terminal-close! source)
     (terminal-close! replay))))

(test-case "write until ground stops at the shortest prefix and distinguishes exhaustion"
  (call-with-terminal
   #:continuation-max-bytes 32
   (lambda (terminal)
     (define-values (ground-consumed ground?) (terminal-write-until-ground! terminal #"unprocessed"))
     (check-equal? (list ground-consumed ground?) '(0 #t))
     (check-equal? (terminal->plain-text terminal) "")
     (terminal-write! terminal #"\33[31")
     (define input #"mABC\33[")
     (define-values (consumed reached?) (terminal-write-until-ground! terminal input))
     (check-equal? (list consumed reached?) '(1 #t))
     (check-equal? (terminal->plain-text terminal) "")
     (check-equal? (terminal-continuation-bytes terminal) #"")
     (terminal-write! terminal (subbytes input consumed))
     (check-equal? (terminal->plain-text terminal) "ABC")
     (define-values (more-consumed more-ground?) (terminal-write-until-ground! terminal #"123"))
     (check-equal? (list more-consumed more-ground?) '(3 #f))
     (check-equal? (terminal-continuation-bytes terminal) #"\33[123")
     (define-values (empty-consumed empty-ground?) (terminal-write-until-ground! terminal #""))
     (check-equal? (list empty-consumed empty-ground?) '(0 #f))
     (define-values (final-consumed final-ground?) (terminal-write-until-ground! terminal #"m"))
     (check-equal? (list final-consumed final-ground?) '(1 #t)))))

(test-case "UTF-8, malformed UTF-8, and CAN produce exact ground boundaries"
  (call-with-terminal #:continuation-max-bytes 32
                      (lambda (terminal)
                        (terminal-write! terminal (bytes #xf0))
                        (define-values (utf8-consumed utf8-ground?)
                          (terminal-write-until-ground! terminal (bytes #x9f #x98 #x84)))
                        (check-equal? (list utf8-consumed utf8-ground?) '(3 #t))
                        (terminal-write! terminal (bytes #xe0 #xa0))
                        (define-values (malformed-consumed malformed-ground?)
                          (terminal-write-until-ground! terminal #"A!"))
                        (check-equal? (list malformed-consumed malformed-ground?) '(1 #t))
                        (terminal-write! terminal #"\33[123")
                        (define-values (can-consumed can-ground?)
                          (terminal-write-until-ground! terminal (bytes #x18 (char->integer #\X))))
                        (check-equal? (list can-consumed can-ground?) '(1 #t))
                        (check-true (terminal-vt-ground? terminal)))))

(test-case "effects run only for consumed input and exceptions remain operation scoped"
  (call-with-terminal
   #:continuation-max-bytes 32
   (lambda (terminal)
     (define bells 0)
     (terminal-set-bell-handler! terminal (lambda () (set! bells (add1 bells))))
     (terminal-write! terminal #"\33[31")
     (define-values (consumed reached?) (terminal-write-until-ground! terminal #"m\a"))
     (check-equal? (list consumed reached?) '(1 #t))
     (check-equal? bells 0)
     (terminal-write! terminal #"\a")
     (check-equal? bells 1)
     (define raised (exn:fail "bell" (current-continuation-marks)))
     (terminal-set-bell-handler! terminal (lambda () (raise raised)))
     (terminal-write! terminal #"\33[")
     (check-eq? (capture-raised (lambda () (terminal-write-until-ground! terminal #"\amX"))) raised)
     (check-true (terminal-vt-ground? terminal))
     (terminal-set-bell-handler! terminal #f)
     (terminal-write! terminal #"X")
     (check-equal? (terminal->plain-text terminal) "X"))))

(test-case "same-terminal continuation calls from an effect callback fail without deadlock"
  (call-with-terminal
   #:continuation-max-bytes 32
   (lambda (terminal)
     (terminal-set-bell-handler! terminal (lambda () (terminal-continuation-bytes terminal)))
     (terminal-write! terminal #"\33[")
     (define error (capture-raised (lambda () (terminal-write-until-ground! terminal #"\am"))))
     (check-true (exn:fail:contract? error))
     (check-regexp-match #rx"same-terminal" (exn-message error))
     (terminal-set-bell-handler! terminal #f)
     (check-true (terminal-vt-ground? terminal)))))

(test-case "representative cuts and chunking replay the same native state"
  (for* ([sample (in-list (list #"\33[38;2;1;2;3mX"
                                (bytes-append (bytes #xf0 #x9f #x98 #x84) #"X")
                                #"\33]2;title\33\\X"))]
         [cut (in-range 1 (bytes-length sample))])
    (define source (make-terminal 40 2 #:continuation-max-bytes 64))
    (define replay (make-terminal 40 2 #:continuation-max-bytes 64))
    (dynamic-wind void
                  (lambda ()
                    (terminal-write! source (subbytes sample 0 cut))
                    (unless (terminal-vt-ground? source)
                      (terminal-write! replay (terminal-continuation-bytes source))
                      (define suffix (subbytes sample cut))
                      (terminal-write! source suffix)
                      (terminal-write! replay suffix)
                      (check-equal? (terminal-vt-ground? source) (terminal-vt-ground? replay))
                      (check-equal? (terminal->plain-text source) (terminal->plain-text replay))))
                  (lambda ()
                    (terminal-close! source)
                    (terminal-close! replay))))
  (define bulk (make-terminal 20 2 #:continuation-max-bytes 32))
  (define chunked (make-terminal 20 2 #:continuation-max-bytes 32))
  (dynamic-wind void
                (lambda ()
                  (define prefix #"\33]2;chunked")
                  (terminal-write! bulk prefix)
                  (for ([byte (in-bytes prefix)])
                    (terminal-write! chunked (bytes byte)))
                  (check-equal? (terminal-continuation-bytes bulk)
                                (terminal-continuation-bytes chunked)))
                (lambda ()
                  (terminal-close! bulk)
                  (terminal-close! chunked))))

(test-case "continuation operations serialize, repeatedly clean up, and reject close"
  (define terminal (make-terminal 20 2 #:continuation-max-bytes 32))
  (for ([_iteration (in-range 500)])
    (check-equal? (terminal-continuation-bytes terminal) #""))
  (define results (make-channel))
  (for ([_worker (in-range 4)])
    (thread (lambda ()
              (with-handlers ([exn? (lambda (error) (channel-put results error))])
                (for ([_iteration (in-range 100)])
                  (terminal-continuation-max-bytes terminal)
                  (terminal-vt-ground? terminal)
                  (terminal-continuation-bytes terminal))
                (channel-put results 'done)))))
  (for ([_worker (in-range 4)])
    (define outcome (sync/timeout 10 results))
    (unless outcome
      (error 'continuation-serialization-test "worker timed out"))
    (when (exn? outcome)
      (raise outcome))
    (check-eq? outcome 'done))
  (define copied (terminal-continuation-bytes terminal))
  (terminal-close! terminal)
  (terminal-close! terminal)
  (check-equal? copied #"")
  (for ([operation (in-list (list (lambda () (terminal-continuation-max-bytes terminal))
                                  (lambda () (terminal-set-continuation-max-bytes! terminal 1))
                                  (lambda () (terminal-continuation-bytes terminal))
                                  (lambda () (terminal-vt-ground? terminal))
                                  (lambda () (terminal-write-until-ground! terminal #"x"))))])
    (check-exn exn:fail:ghostty:closed? operation)))
