#lang racket/base

(require ffi/unsafe
         "loader.rkt")

(provide GHOSTTY-BUILD-INFO-SIMD
         GHOSTTY-BUILD-INFO-KITTY-GRAPHICS
         GHOSTTY-BUILD-INFO-TMUX-CONTROL-MODE
         GHOSTTY-BUILD-INFO-OPTIMIZE
         GHOSTTY-BUILD-INFO-VERSION-STRING
         GHOSTTY-BUILD-INFO-VERSION-MAJOR
         GHOSTTY-BUILD-INFO-VERSION-MINOR
         GHOSTTY-BUILD-INFO-VERSION-PATCH
         GHOSTTY-BUILD-INFO-VERSION-PRE
         GHOSTTY-BUILD-INFO-VERSION-BUILD
         ghostty-build-info)

(define GHOSTTY-BUILD-INFO-SIMD 1)
(define GHOSTTY-BUILD-INFO-KITTY-GRAPHICS 2)
(define GHOSTTY-BUILD-INFO-TMUX-CONTROL-MODE 3)
(define GHOSTTY-BUILD-INFO-OPTIMIZE 4)
(define GHOSTTY-BUILD-INFO-VERSION-STRING 5)
(define GHOSTTY-BUILD-INFO-VERSION-MAJOR 6)
(define GHOSTTY-BUILD-INFO-VERSION-MINOR 7)
(define GHOSTTY-BUILD-INFO-VERSION-PATCH 8)
(define GHOSTTY-BUILD-INFO-VERSION-PRE 9)
(define GHOSTTY-BUILD-INFO-VERSION-BUILD 10)

(define-ghostty ghostty-build-info (_fun _int _pointer -> _int) #:c-id ghostty_build_info)
